name: Test code quality

on:
  pull_request:
    branches:
      - staging
      - prod
      - "TESS-**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Test run
        run: echo "Testing"

      - name: Install dependencies
        working-directory: ./source/app
        run: npm install

      - name: Run Jest tests
        working-directory: ./source/app
        run: npm run test

      - name: Run ESLint
        working-directory: ./source/app
        run: npm run lint
        
#
#    - name: Check ESLint and Jest passing rate
#      working-directory: ./source/app
#      run: |
#        eslint_result=$(npx eslint --format=summary . | grep 'problem' | awk '{print $NF}')
#        jest_result=$(cat coverage/lcov.info | npx coveralls)
#        if [ "$eslint_result" -eq 0 ] && [ "$jest_result" -ge 90 ]; then
#          echo "All tests passed"
#          exit 0
#        else
#          echo "ESLint or Jest tests failed"
#          exit 1
#        fi