name: Backup Prod to Main within certain timeframe

on:
  schedule:
    - cron: "0 0 1 * *" # Backup on the 1st of every month

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  backup_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Prod
        uses: actions/checkout@v3

      - name: Merge branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: prod
          target_branch: main
          github_token: ${{ github.token }}
