name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Create zip release of the main branch
      #   run: |
      #     zip -r release.zip .

      # - name: Upload zip to GitHub release
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: release.zip
      #     asset_name: release.zip
      #     asset_content_type: application/zip
