name: Update staging branch on release

on:
  release:
    types: [published]

jobs:
  update-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main # update this to the main branch name of the current repository

    - name: Get repository name and latest tag
      id: get-details
      run: echo ::set-output name=details::$(echo "${GITHUB_REPOSITORY}=$(git describe --tags)")

    - name: Checkout staging branch in other repository
      uses: actions/checkout@v2
      with:
        repository: postroad-energy/tess-core
        ref: staging # update this to the name of the staging branch in the other repository
        token: ${{ secrets.ACCESS_TOKEN }} # update this to the name of the secret containing the access token for the other repository

    - name: Update text file with latest release details
      run: |
        details="${{ steps.get-details.outputs.details }}"
        repository=$(echo "$details" | cut -d'=' -f1)
        sed -i "s/^$repository=.*$/$details/" release.txt
        if ! grep -q "^$repository=" release.txt; then echo "$details" >> release.txt; fi
        git add release.txt
        git commit -m "Update release details for $details"
        git push origin staging